# Generated by Django 4.2 on 2024-05-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0007_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('growth_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RevenueShare.growthshare')),
                ('mlos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter')),
            ],
        ),
    ]
