# Generated by Django 4.2.2 on 2024-07-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0002_ahf_company_loanamount_mlo_agent_recruiter_and_more"),
        ("RevenueShare", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualRevenueShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField()),
                ("amount", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="HyperGrowthShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField()),
                ("amount", models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="revenueshare",
            name="ahf_charity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="revenueshare",
            name="recruiter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruiter.recruiter",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="revenueshare",
            name="mlos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recruiter.mlo"
            ),
        ),
        migrations.AddField(
            model_name="revenueshare",
            name="annual_revenue_share",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="RevenueShare.annualrevenueshare",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revenueshare",
            name="hyper_growth_share",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="RevenueShare.hypergrowthshare",
            ),
            preserve_default=False,
        ),
    ]
