# Generated by Django 4.2 on 2024-05-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueShare', '0003_node_edge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
