# Generated by Django 5.0.4 on 2024-04-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0007_alter_branchpayrollliabilities_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchpayrollliabilities',
            name='Employment_Training_Tax',
            field=models.FloatField(verbose_name='Employment Training Tax (ETT)'),
        ),
    ]
