# Generated by Django 5.0.4 on 2024-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0010_rename_employeewithholdings_employeewithholding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeewithholding',
            options={'verbose_name': 'Employee Withholding', 'verbose_name_plural': 'Employee Withholding'},
        ),
        migrations.AlterField(
            model_name='employeewithholding',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
