# Generated by Django 5.0.4 on 2024-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0012_branchpayrollliabilitiesq'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpayrollliabilitiesq',
            name='Q_value',
            field=models.CharField(default='Q31', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
