# Generated by Django 5.0.4 on 2024-04-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0013_branchpayrollliabilitiesq_q_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpayrollliabilitiesq',
            name='bpql',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='W2branchYearlyGross.branchpayrollliabilities'),
            preserve_default=False,
        ),
    ]
