# Generated by Django 5.0.4 on 2024-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0016_branchpayrollliabilitier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPayrollLiabilitieQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Security', models.FloatField(verbose_name='Social Security')),
                ('Medicare', models.FloatField()),
                ('Fed_Unemploy', models.FloatField()),
                ('CA_Unemployment', models.FloatField(verbose_name='CA Unemployment')),
                ('Employment_Training_Tax', models.FloatField(verbose_name='Employment Training Tax (ETT)')),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BranchPayrollLiabilitiesQ',
        ),
    ]
