# Generated by Django 5.0.4 on 2024-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0018_q22'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWithholdingQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Security', models.FloatField()),
                ('Medicare', models.FloatField()),
                ('CA_disability', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Withholding',
                'verbose_name_plural': 'Employee Withholding',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWithholdingR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Security', models.FloatField()),
                ('Medicare', models.FloatField()),
                ('CA_disability', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Withholding',
                'verbose_name_plural': 'Employee Withholding',
            },
        ),
    ]
