# Generated by Django 4.2.2 on 2024-07-28 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recruiter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AHF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission", models.FloatField()),
                ("loan_per_year", models.IntegerField(default=1)),
                ("loan_per_month", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1000, null=True)),
                ("cap", models.FloatField()),
                ("company_commission", models.FloatField()),
                ("number_of_loans", models.IntegerField(blank=True, null=True)),
                ("total", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LoanAmount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recruiter_id", models.IntegerField()),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loan_date", models.DateField()),
                ("repayment_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MLO_AGENT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NMLS_ID", models.IntegerField()),
                ("NMLS_sponsor_id", models.IntegerField(blank=True, null=True)),
                ("MLO_commission", models.FloatField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now=True)),
                ("year_to_date", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="mlo",
            name="NMLS_ID",
        ),
        migrations.RemoveField(
            model_name="mlo",
            name="NMLS_sponsor_id",
        ),
        migrations.RemoveField(
            model_name="mlo",
            name="name",
        ),
        migrations.AddField(
            model_name="mlo",
            name="level",
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("node_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "mlo_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruiter.mlo_agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanBreakPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_break_point", models.FloatField(default=1000000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruiter.loanamount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("edge_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="recruiter.node",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="recruiter.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Flat_Fee", models.FloatField(default=0)),
                ("Percentage", models.FloatField()),
                ("Minimum_Compensation", models.FloatField(default=2.75)),
                ("Maximum_Compensation", models.FloatField(default=2750)),
                ("MAX_GCI", models.FloatField(default=27500)),
                ("FF_MIN_LOAN", models.IntegerField(default=27500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=10),
                ),
                ("loan_per_year", models.IntegerField(blank=True, null=True)),
                ("loan_per_month", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bps", models.FloatField(default=275)),
                ("interval", models.IntegerField(default=50)),
                ("max_value", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
