# Generated by Django 4.2.2 on 2024-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0002_ahf_company_loanamount_mlo_agent_recruiter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="amount",
        ),
        migrations.AddField(
            model_name="loan",
            name="amount",
            field=models.ManyToManyField(default=1, to="recruiter.loanamount"),
        ),
    ]
