# Generated by Django 5.0.4 on 2024-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_bps_bps_alter_compplan_flat_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=10),
        ),
    ]
