# Generated by Django 4.2 on 2024-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_alter_branch_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='compplan',
            name='FF_MIN_LOAN',
            field=models.IntegerField(null=True),
        ),
    ]
