# Generated by Django 4.2.2 on 2024-07-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0004_alter_loan_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="user",
            new_name="mlo_agent",
        ),
    ]
