# Generated by Django 4.2.2 on 2024-07-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0005_rename_user_loan_mlo_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanamount",
            name="recruiter_id",
        ),
    ]
