# Generated by Django 4.2 on 2024-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_compplan_ff_min_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compplan',
            name='FF_MIN_LOAN',
            field=models.IntegerField(default=27500),
        ),
    ]
