# Generated by Django 4.2 on 2024-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlo',
            name='MLO_commision',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='NMLS_ID',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='NMLS_sponsor_id',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='annual_commision_paid_to_company',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='break_point',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='gci',
        ),
        migrations.RemoveField(
            model_name='mlo',
            name='name',
        ),
        migrations.AddField(
            model_name='mlo',
            name='level',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
