# Generated by Django 4.2.2 on 2024-08-01 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0007_loan_bps"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="Date_funded",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="File_reference",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
