# Generated by Django 4.2.2 on 2024-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0008_loan_date_funded_loan_file_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="Date_funded",
            field=models.DateField(auto_now_add=True),
        ),
    ]
