# Generated by Django 4.2 on 2024-05-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0009_rename_level_recruiter_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_closed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MLO_AGENT',
            fields=[
                ('NMLS_ID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('joined_date', models.DateTimeField(auto_now=True)),
                ('NMLS_ID_SPONSOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.mlo_agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLO_AGENT_PRODUCTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMLS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.mlo_agent')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.loans')),
            ],
        ),
        migrations.AddField(
            model_name='loans',
            name='NMLS_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.mlo_agent'),
        ),
    ]
