# Generated by Django 4.2.2 on 2024-08-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0009_alter_loan_date_funded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="Date_funded",
            new_name="date_funded",
        ),
    ]
