# Generated by Django 5.0.6 on 2024-06-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_rename_level_recruiter_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('edge_label', models.CharField(max_length=255)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='recruiter.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='recruiter.node')),
            ],
        ),
    ]
