# Generated by Django 4.2.2 on 2024-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0010_rename_date_funded_loan_date_funded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="date_funded",
        ),
    ]
