# Generated by Django 5.0.6 on 2024-06-06 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_node_edge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLO_AGENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMLS_ID', models.IntegerField(blank=True, null=True)),
                ('NMLS_sponsor_id', models.IntegerField(blank=True, null=True)),
                ('MLO_commision', models.FloatField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
