# Generated by Django 4.2.2 on 2024-08-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0011_remove_loan_date_funded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="File_reference",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.ManyToManyField(
                default=1, related_name="loans", to="recruiter.loanamount"
            ),
        ),
    ]
