# Generated by Django 5.0.6 on 2024-06-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_mlo_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_label',
        ),
        migrations.AddField(
            model_name='node',
            name='mlo_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.mlo_agent'),
            preserve_default=False,
        ),
    ]
