# Generated by Django 4.2 on 2024-06-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_node_edge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='weight',
            new_name='production',
        ),
    ]
