# Generated by Django 4.2 on 2024-06-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_delete_node_rename_weight_edge_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='recruiter.mlo_agent', unique=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='recruiter.mlo_agent', unique=True),
        ),
    ]
