# Generated by Django 4.2.2 on 2024-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0012_alter_loan_file_reference_alter_loan_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanamount",
            name="File_reference",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
