# Generated by Django 5.0.6 on 2024-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_remove_node_node_label_node_mlo_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='edge_label',
        ),
    ]
