# Generated by Django 5.0.6 on 2024-06-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_remove_edge_edge_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlo_agent',
            old_name='MLO_commision',
            new_name='MLO_commission',
        ),
    ]
