# Generated by Django 4.2.2 on 2024-09-24 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0013_loanamount_file_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="date_closed",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
