# Generated by Django 4.2 on 2024-06-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_alter_edge_from_node_alter_edge_to_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlo_agent_production',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
