# Generated by Django 4.2 on 2024-06-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_mlo_agent_production_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlo_agent_production',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.loans'),
        ),
    ]
