# Generated by Django 4.2.2 on 2024-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0014_loan_date_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="date_closed",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
