# Generated by Django 4.2.2 on 2024-09-24 05:58

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0015_alter_loan_date_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(verbose_name=builtins.min)),
            ],
        ),
    ]
