# Generated by Django 5.0.6 on 2024-06-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_mlo_agent_year_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='loan',
            name='mlo_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.mlo_agent'),
            preserve_default=False,
        ),
    ]
