# Generated by Django 4.2 on 2024-06-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_alter_mlo_agent_production_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='recruiter.mlo_agent'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='recruiter.mlo_agent'),
        ),
    ]
