# Generated by Django 5.0.6 on 2024-06-09 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0016_remove_loan_user_loan_mlo_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_closed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
