# Generated by Django 4.2 on 2024-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0016_alter_edge_from_node_alter_edge_to_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('neighbors', models.ManyToManyField(blank=True, to='recruiter.node')),
            ],
        ),
    ]
