# Generated by Django 4.2.2 on 2024-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0017_loansetting_user_alter_loansetting_month"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name="mlo_agent",
        #     old_name="year_to_date",
        #     new_name="flat_Fee",
        # ),
        # migrations.AddField(
        #     model_name="mlo_agent",
        #     name="max",
        #     field=models.FloatField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name="mlo_agent",
            name="NMLS_sponsor_id",
            field=models.CharField(default="567890-09", max_length=100),
            preserve_default=False,
        ),
    ]
