# Generated by Django 4.2 on 2024-06-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AddField(
            model_name='node',
            name='mlo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.mlo_agent'),
        ),
    ]
