# Generated by Django 4.2.2 on 2024-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recruiter",
            "0018_rename_year_to_date_mlo_agent_flat_fee_mlo_agent_max_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mlo_agent",
            old_name="year_to_date",
            new_name="flat_Fee",
        ),
        migrations.AddField(
            model_name="mlo_agent",
            name="max",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
