# Generated by Django 4.2 on 2024-06-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0018_remove_node_name_node_mlo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='MLONode',
        ),
    ]
