# Generated by Django 4.2 on 2024-06-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0019_rename_node_mlonode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlonode',
            name='mlo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mlo_node', to='recruiter.mlo_agent'),
        ),
    ]
