# Generated by Django 4.2.2 on 2024-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0019_rename_year_to_date_mlo_agent_flat_fee_mlo_agent_max"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlo_agent",
            name="max",
            field=models.CharField(
                blank=True,
                choices=[("1", "Option 1"), ("2", "Option 2"), ("3", "Option 3")],
                max_length=4,
                null=True,
            ),
        ),
    ]
