# Generated by Django 4.2.2 on 2024-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0020_alter_mlo_agent_max"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlo_agent",
            name="NMLS_ID",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mlo_agent",
            name="max",
            field=models.CharField(
                blank=True,
                choices=[
                    (50, 50),
                    (75, 75),
                    (100, 100),
                    (125, 125),
                    (150, 150),
                    (175, 175),
                    (200, 200),
                    (225, 225),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
