# Generated by Django 4.2.2 on 2024-10-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recruiter", "0021_alter_mlo_agent_nmls_id_alter_mlo_agent_max"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlo_agent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_mlo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
