# Generated by Django 4.2.2 on 2024-10-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0022_alter_mlo_agent_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="mlo_agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_mlo",
                to="recruiter.mlo_agent",
            ),
        ),
    ]
