# Generated by Django 4.2.2 on 2024-10-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0023_alter_node_mlo_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bps",
            name="max_value",
            field=models.FloatField(default=275),
        ),
    ]
