# Generated by Django 4.2.2 on 2024-10-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0024_alter_bps_max_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compplan",
            name="Percentage",
            field=models.FloatField(default=2.75),
        ),
    ]
