# Generated by Django 4.2.2 on 2024-10-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0025_alter_compplan_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="mlo_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mlo_loans",
                to="recruiter.mlo_agent",
            ),
        ),
    ]
