# Generated by Django 4.2.2 on 2024-10-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0026_alter_loan_mlo_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanamount",
            name="order_of",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
