# Generated by Django 4.2.2 on 2024-10-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0027_loanamount_order_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanamount",
            name="memo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
