# Generated by Django 4.2.2 on 2024-10-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0028_loanamount_memo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="edge_id",
        ),
        migrations.AddField(
            model_name="edge",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mlo_agent",
            name="max",
            field=models.CharField(
                blank=True,
                choices=[
                    ("50", 50),
                    ("75", 75),
                    ("100", 100),
                    ("125", 125),
                    ("150", 150),
                    ("175", 175),
                    ("200", 200),
                    ("225", 225),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
