# Generated by Django 4.2.2 on 2024-10-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0029_remove_edge_edge_id_edge_id_alter_mlo_agent_max"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="mlo_agent",
        ),
        migrations.AddField(
            model_name="mlo_agent",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mlo_loans",
                to="recruiter.loan",
            ),
        ),
    ]
