# Generated by Django 4.2.2 on 2024-10-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0030_remove_loan_mlo_agent_mlo_agent_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="File_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
