# Generated by Django 4.2.2 on 2024-10-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0031_alter_loan_file_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mlo_agent",
            name="flat_Fee",
        ),
    ]
