# Generated by Django 5.0.4 on 2024-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWithHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Security', models.FloatField()),
                ('Medicare', models.FloatField()),
                ('CA_disability', models.FloatField()),
            ],
        ),
    ]
