# Generated by Django 5.0.4 on 2024-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0004_employeewithholdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeewithholdings',
            name='total',
            field=models.FloatField(default=3134123),
            preserve_default=False,
        ),
    ]
