# Generated by Django 5.0.4 on 2024-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0006_branchpayrollliabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchpayrollliabilities',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
