# Generated by Django 5.0.4 on 2024-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2branchYearlyGross', '0011_alter_employeewithholding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPayrollLiabilitiesQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
    ]
