# Generated by Django 5.0.4 on 2024-04-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AHF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField()),
                ('loan_per_year', models.IntegerField(default=1)),
                ('loan_per_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bps', models.FloatField()),
                ('interval', models.IntegerField(default=50)),
                ('max_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_per_year', models.IntegerField(blank=True, null=True)),
                ('loan_per_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('cap', models.FloatField()),
                ('company_commission', models.FloatField()),
                ('number_of_loans', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CompPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flat_Fee', models.FloatField()),
                ('Percentage', models.FloatField()),
                ('Minimum_Compensation', models.FloatField()),
                ('Maximum_Compensation', models.FloatField()),
                ('MAX_GCI', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanBreakPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_break_point', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='mlo',
            name='MLO_commision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlo',
            name='annual_commision_paid_to_company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlo',
            name='break_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlo',
            name='comp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlo',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mlo',
            name='gci',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        
        
      
    ]
