# Generated by Django 5.0.4 on 2024-04-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_company_loan_mlo_mlo_commision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_loans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
