# Generated by Django 5.0.4 on 2024-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_ahf_bps_branch_company_compplan_loanbreakpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bps',
            name='bps',
            field=models.FloatField(default=275),
        ),
        migrations.AlterField(
            model_name='compplan',
            name='Flat_Fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compplan',
            name='MAX_GCI',
            field=models.FloatField(default=27500),
        ),
        migrations.AlterField(
            model_name='compplan',
            name='Maximum_Compensation',
            field=models.FloatField(default=2750),
        ),
        migrations.AlterField(
            model_name='compplan',
            name='Minimum_Compensation',
            field=models.FloatField(default=2.75),
        ),
        migrations.AlterField(
            model_name='loanbreakpoint',
            name='loan_break_point',
            field=models.FloatField(default=1000000),
        ),
    ]
