# Generated by Django 5.0.4 on 2024-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_loan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleLenderCompPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flat_Fee', models.FloatField()),
                ('Percentage', models.FloatField()),
                ('Minimum_Compensation', models.FloatField()),
                ('Maximum_Compensation', models.FloatField()),
            ],
        ),
    ]
