# Generated by Django 5.0.4 on 2024-04-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_loanbreakpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WholesaleLenderCompPlan',
            new_name='CompPlan',
        ),
    ]
