# Generated by Django 5.0.4 on 2024-04-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_rename_wholesalelendercompplan_compplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField()),
            ],
        ),
    ]
