# Generated by Django 5.0.4 on 2024-04-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_alter_branch_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='compplan',
            name='MAX_GCI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
