# Generated by Django 5.0.4 on 2024-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_compplan_max_gci'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbreakpoint',
            name='loand_per_year',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
