# Generated by Django 5.0.4 on 2024-04-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_loanbreakpoint_loand_per_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbreakpoint',
            name='loand_per_year',
        ),
        migrations.AddField(
            model_name='loanbreakpoint',
            name='loan_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanbreakpoint',
            name='loan_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
