# Generated by Django 5.0.4 on 2024-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_remove_loanbreakpoint_loand_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbreakpoint',
            name='loan_per_month',
        ),
        migrations.RemoveField(
            model_name='loanbreakpoint',
            name='loan_per_year',
        ),
        migrations.AddField(
            model_name='ahf',
            name='loan_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahf',
            name='loan_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='loan_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='loan_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
