# Generated by Django 4.2.2 on 2024-10-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruiter", "0032_remove_mlo_agent_flat_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NMLS_sponsor_id", models.CharField(max_length=100)),
                ("NMLS_ID", models.CharField(max_length=100)),
                ("MLO_commission", models.FloatField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now=True)),
                (
                    "max",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("50", 50),
                            ("75", 75),
                            ("100", 100),
                            ("125", 125),
                            ("150", 150),
                            ("175", 175),
                            ("200", 200),
                            ("225", 225),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_loans",
                        to="recruiter.loan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_agent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
